### ISSUE TITLE
E2E-Test ShowTop10Customers() 2 vm. prefixes missing

### ISSUE THREAD

**Issue by RoDo777** [DanWahlin/CustomerManagerStandard#23]
```javascript
public void ShowTop10Customers()
...
    .("customer in vm.filteredCustomers"));  // add "vm." (line 65)
...
    .FindElement(NgBy.Binding("vm.totalRecords"));   //add vm. (line 68)
```

Sorry, I don't know how to bring this changes into your code. I think fork and then edit my version, but didn't looked up how to request that you can merge my changes into your master ...

**Comment by DanWahlin** [comment]
Yep, you can fork the project, edit your version, and do a pull request to this project. Love to get these changes in so if you end up having time to do that let me know. Really appreciate it especially since the project has been updated quite a bit but I haven't revisited the E2E tests that someone else initially contributed.
